name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: lazy test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rev: nightly/nvim-linux64.tar.gz
            manager: sudo apt-get
            # packages: -y ripgrep
          - os: ubuntu-latest
            rev: v0.9.0/nvim-linux64.tar.gz
            manager: sudo apt-get
            # packages: -y ripgrep
    steps:
      - uses: actions/checkout@v3
      - run: date +%F > todays-date
      - name: Restore from todays cache
        uses: actions/cache@v3
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.rev }}-${{ hashFiles('todays-date') }}

      - name: Prepare
        run: |
          ${{ matrix.manager }} update
          # ${{ matrix.manager }} install ${{ matrix.packages }}
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/${{ matrix.rev }}" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
          echo "Downloading lazy.nvim config"
          mkdir -p ~/.config/nvim/lua/config
          curl -sL "https://raw.githubusercontent.com/LazyVim/starter/main/lua/config/lazy.lua" > ~/.config/nvim/lua/config/lazy.lua
          echo "Downloading pablopunk's unclutter config"
          mkdir -p ~/.config/nvim/lua/config/plugins
          curl -sL "https://raw.githubusercontent.com/pablopunk/dotfiles/master/nvim/lua/pablopunk/plugins/unclutter.lua" > ~/.config/nvim/lua/config/plugins/unclutter.lua

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --headless +qa
          nvim --headless "+Lazy! install" +qa
          nvim --headless +qa
